server:
  port: 8170 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: guli-order # 服务名
  datasource: # mysql数据库连接
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://192.168.148.129:3306/db_order?characterEncoding=utf-8&useSSL=false
    username: root
    type: com.zaxxer.hikari.HikariDataSource # 连接池类型
    hikari:
      pool-name: GuliHikariPool # 连接池名称，默认HikariPool-1
      maximum-pool-size: 12 # 最大连接数，小于等于0会被重置为默认值10；大于零小于1会被重置为minimum-idle的值
      connection-timeout: 60000 # 连接超时时间:毫秒，小于250毫秒，否则被重置为默认值30秒
      minimum-idle: 10 # 最小空闲连接，默认值10，小于0或大于maximum-pool-size，都会重置为maximum-pool-size
      idle-timeout: 500000 # 空闲连接超时时间，默认值600000（10分钟），大于等于max-lifetime且max-lifetime>0，会被重置为0；不等于0且小于10秒，会被重置为10秒。
      # 只有空闲连接数大于最大连接数且空闲时间超过该值，才会被释放
      max-lifetime: 540000 # 连接最大存活时间.不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短
      connection-test-query: SELECT 1 #连接测试查询

  jackson: #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #mybatis日志
  #mybatis-plus:
  mapper-locations: classpath:com/atguigu/guli/service/order/mapper/xml/*.xml #配置mapper xml文件的路径

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9110/eureka/
    #缓存服务注册表中的信息,有效地缓解Eureka Server的压力
    #从注册中心获取注册信息，默认true
    fetchRegistry: true
    # 从注册中心获取注册信息的时间间隔，默认30s
    registryFetchIntervalSeconds: 30
  instance:
    prefer-ip-address: true
    # 心跳检测检测与续约时间
    # 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
    # 配置说明
    # lease-renewal-interval-in-seconds 每间隔5s，向服务端发送一次心跳，证明自己依然”存活“，默认 30
    lease-renewal-interval-in-seconds: 5
    # lease-expiration-duration-in-seconds  告诉服务端，如果我10s之内没有给你发心跳，就代表我“死”了，将我踢出掉，默认 90
    lease-expiration-duration-in-seconds: 10

weixin:
  pay:
    #关联的公众号appid
    appid: wx74862e0dfcf69954
    #商户号
    partner: 1558950191
    #商户key
    partnerkey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
    #回调地址
    notifyurl: http://yitian.free.idcfengye.com/web/weixin-pay/callback/notify

alipay:
  app_id: 2016101600698778
  merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCZmOm1mtVo5z9uvrUaektnBX8+FG9bpWqx2hd81GKVk6eFzQ/UJxAO9+EmCFc7UPI0xY2a/H73MQhRRVXPaxs3C7e48XT5sVvDupqbm8m5Ucy7BPXHXDqislZ11egXDfw1jpVbMV9zBpg87owAj6fnvijg3Qw6WL1F0m6y3PYYZ9X3Gvtl+knelRhErsotiN/LgnVJJCru/Rss+ZokRuZt6s4zFKBBqkGVDgmVNdzX+ag1NouKxY+2AybUFKDZsD/ECc5vFMKfrKBkOo5/Qc08dj2XytAGFl2t4HhRdXU+/VDHDpIe4VieA0OxrjnWwzeKDazBd2BYvfzQHEeBzJ09AgMBAAECggEAbZB7XfUVuGAEip31F+8WrGVqb8Ep8kjcBAQbbwsdS69o93Pgj6hRtyuw6m1WtFQ4gdZN/bmRZAkQ8tAvtuajIi/0nTN4CskuOT96G/gT/GLSVLHkFJLArN/j9uhgR1nNh/Kurb9ZY/bXT9el/Jx83D10cXqcx14XnZ/PIT2nOp50JFpE5cAilBdf1OwAgNrD/XAsSweZ1KKS5MMwgQHbOfMjDKaiqAwlsxINlnA1OzaAQ7AS6632oYA8U3cLQRiQR4acDKdmEgPRgY+ElIcKsF1ipVdCY97evUDEtxb+GRp0Bqjq4NbBZZcWeiLLdk/Y2HNwi6DMTE8PQ35lTrfWzQKBgQDMgmuyclBBoex+nsScjSiUhB9kjySmHQiS5j34fn+FaYeAR6HUsTotTzk5TiL6CIPxaPbFmKzsSnuKk5DUAx11jacvehiOTTtqu9nfIfHJdTUHiT4dy1wjXJDM5p2+pmJZ90a1CC7+QIKEDSqm+4fYunHn8h0/rBVxtC+yG7XUTwKBgQDARPg4GhWA3iAxL2+PxOIucNsx6nIB5yD+t0xYex+2P1uHRB+19+iuADXKdwBVvU7kRoLXMO3aLZMLmSXxL/zFeD2o7tJ5D4fr4dwTfm8NRYbRNLOnga9J7d5omAby3Aud5BB3uQfjPL98xJG8p41+bZXnaau7cCViIPVhFHe2swKBgAraaQjBVE0HYNufZWPBggPPtzLI/fLq24egPG2xmObloNFH++ijtyisaacG5IhMZ2QqY948qgCoO0IxbqAxwiB48gRtAFyc8KhLa9aRoJlGZRgPSoKeRjeCNBULsBdsERAhNVlqI8ROfB6x7C+MbbssudrLWI4GfeTY4SccnVu1AoGAA1UuuEo7dTBkfnXECUnwYb2zDvpxX3cSK1giCqaXtiEDBSU5J35Umi+Gvyuw5cuSQoK2YeSHOvDvS5QsBDJAv2uGJhd9rnuGb6BKoEvgwOojnBy9wHmPAEkPQeDgvfTyfpolbu3WJSo4Z4FAxXRiD372yjwarfUTsM/BcR1ZteECgYEAsFp3hTa1Kh8y6R/q3/oF8mDQW2KhqikJ9aaHF6Y0sDgtFZdBybJDCRvhpw2NGWUeItWB0i170RImtKF/AgcHlEPJOnsbMc/VMM3eWAolqkTJqaw+/AjI0B3RwVumhN2kmOWLSnlGJwm/KsxdOsWGjb5dsttQ+XWg9O547zoJ/2E=
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2/8XpW4VHvgKPJpjAfrJ0M33LT76wmbjdTaXDRGiaFQ8ZaldBalmuyetz9R5/wbZJi9KIYkFAZx6IMO7JJu4A/6dtYluHK17XceF1Lo8xVjYhoRfarMoqoYbsOsNuSo/w3gDMt5c2kpjBCqdMmLbo4KVbSn+9j8E/lKRMWO7a9qVYuFHsoryNska3WLuNsdvDi5WgWhAHJ9EL1cw9Nr/G6HeHMbx12BOWdx120+Fwexjz7hmD2TzY3Qu6JIZNy/NAG/HA0cU+jHftNv9yY93ljhDHuApFIn7aUPOsJ/MkwwuoFdwKBaixwyQz5qE6fCecYZxE1Q0P+AHprCOR/DrcQIDAQAB
  notify_url: http://yitian.free.idcfengye.com/web/aliyun-pay/callback/notify # 域名是ngrok提供的域名，路径是订单支付成功回调的路径
  return_url: http://localhost:2000/pay/success.html
  sign_type: RSA2
  charset: utf-8
  gatewayUrl: https://openapi.alipaydev.com/gateway.do